### ISSUE TITLE
Which timeout influences get_strategy_statistic?

### ISSUE THREAD

**Issue by marcfon** [timelyart/Kairos#46]
Which timeout should be increased in kairos.cfg when you get the `get_strategy_statistic: Timeout waiting for has_gone_stale` error?

After this error the backtest isn't progressing anymore. Even after waiting for quite a while.

**Comment by timelyart** [comment]
Did the error provide any additional information?

**Comment by marcfon** [comment]
I've had the issue occur today a few times again. Here's the full stacktrace.

```
2021-12-20 14:41:18.061 ERROR tv - get_strategy_statistic: Timeout waiting for has_gone_stale
Traceback (most recent call last):
  File "/kairos272/tv/tv.py", line 4226, in get_strategy_statistic
    wait_for_element_is_stale(previous_elements[key])
  File "/kairos272/kairos/tools.py", line 319, in wait_for_element_is_stale
    wait_for(has_gone_stale)
  File "/kairos272/kairos/tools.py", line 294, in wait_for
    raise Exception(
Exception: Timeout waiting for has_gone_stale
```

**Comment by timelyart** [comment]
May I ask what the specs of your machine are including the resolution of your display?
Also, are you using the machine for anything else whilst running Kairos?

**Comment by marcfon** [comment]
> Can I ask you what the specs of your machine are? Also, are you using the machine for anything else whilst running Kairos?

It's happening on different machines (both macs) with different specs. The errors happen in the middle of the night when nothing else is running and also during day when running multiple processes. So not much to go on.

<del>What I've noticed is that the backtesting process does continue at some point but the output will be missing dozens of pairs depending on how long it too for the process to pick back up.</del>

**Comment by marcfon** [comment]
I think I have a clue where to look for this. Could it be related having pairs on your watchlist that don't exist on TV?

**Comment by timelyart** [comment]
I just tested this but all I get is a:

`Strategy resulted in a data error. Please make sure the strategy runs for the selected symbol BINANCE:BZRXBTC and timeframe 'D'`

So, I highly doubt that was the issue. The reason I asked for your specs is that `stale` errors may occur because the page doesn't load quickly enough. The root of the problem is that TV updates the underlying data with quite a fast interval, so the elements get updated before Kairos has read them, resulting in these errors.

**Comment by marcfon** [comment]
Did you also try it with `verify_market_listing: no`?

**Comment by timelyart** [comment]
> Did you also try it with `verify_market_listing: no`?

The `verify_market_listing` is only used when generating **_signals_** and _**alerts**_. I tried anyway and it indeed makes no difference.

**Comment by timelyart** [comment]
Did you try with a subset where all the markets are (still) listed? Did that work for you?

**Comment by marcfon** [comment]
Although it's no guarantee that it won't happen in the future, watchlist with only valid pairs haven't throw this timeout over here.

**Comment by timelyart** [comment]
For `signals` and `alerts` I do check for _invalid markets_, so it shouldn't be too hard to add this check for `backtesting` as well.
I've opened a new issue #52  to deal with this bug.

**Comment by timelyart** [comment]
Is this working as expected for you now?

**Comment by marcfon** [comment]
> Is this working as expected for you now?

Just tested with v2.75 and an invalid pair in my watchlist. What happens is that the backtest just hangs when it reaches the invalid pair. No error or timeout. It seems it just keeps waiting.

**Comment by timelyart** [comment]
By chance, I have found a bug in the method that verifies whether a market is valid. Kairos would at times go into an infinite loop when it could find the element with the value but the value itself was empty. This bug seems to be a likely candidate for the behavior you described.

I am going on a limb here and say [version 2.81](https://github.com/timelyart/Kairos/releases/tag/v2.81) has fixed this. If not, please reopen.
