### ISSUE TITLE
Bitfinex exchange alerts

### ISSUE THREAD

**Issue by builtToTrade** [timelyart/Kairos#5]
**Is your feature request related to a problem? Please describe.**
Bitfinex exchange alerts would be a great addition due the more advanced order types available on Bitfinex such as Stop Limit orders, Trailing Stops and leverage.

**Describe the solution you'd like**
Similar to the Polo, Trex and Binance alerts on TRI, Finex data would be super.

**Describe alternatives you've considered**
Many of the DavO alerts are good across multiple exchanges, so I can paper trade on Finex based on Binance alerts, so long as Finex supports the same.

**Comment by timelyart** [comment]
The signals that I forward to TRI are signals I myself wish to see. For now, and unfortunately for you, I'm not interested in the Bitfinex markets as I do not trade there, which is due to their opaqueness. It's not that I do not want to provide those signals, but in doing so I'd introduce noise for myself.

The good news is that Kairos is built so you can generate signals - any signals - for yourself, by yourself. 
I invite you to install and try it out yourself. I'd be happy to be of assistance if needed (just PM me on TRI).
