### ISSUE TITLE
Setting of date field fails in backtest

### ISSUE THREAD

**Issue by mrcrdwd** [timelyart/Kairos#83]
I've done some debugging but couldn't yet fix this one. It seems like the date picker element loses its focus after it has been cleared. So the `set_value()` that follows the `clear()` fails with an `StaleElementReferenceException`.

It's also hard to detect if you're dealing with a date picker, as that's just a glorified text field.

The StaleElementReferenceException doesn't show up in the log, by the way, so you won't notice that setting of the field has failed. Not sure what would be the right way to go about this, but this is something that definitely should be logged as a warning or error.

I'm testing with the most basic pine script that just has a date picker:
```date_picker = input.time(timestamp("1 Feb 2022 12:00"), title="Select start date")```

**Comment by mrcrdwd** [comment]
Another quirky thing is that TV automatically inserts the`-` when manually entering a date. This might mean that dates need to be defined without the `-` in the backtest so, such as `20220101` for instance. This might be influenced though by how long the delay is between the keystrokes.

**Comment by timelyart** [comment]
> I've done some debugging but couldn't yet fix this one. It seems like the date picker element loses its focus after it has been cleared. So the `set_value()` that follows the `clear()` fails with an `StaleElementReferenceException`.

`StaleElementReferenceException` happens when the element is no longer up-to-date, or has gone stale.
 > It's also hard to detect if you're dealing with a date picker, as that's just a glorified text field.

It has become more uniform over the years but TV still knows how to throw a challenge once in a while. 
> The StaleElementReferenceException doesn't show up in the log, by the way, so you won't notice that setting of the field has failed. Not sure what would be the right way to go about this, but this is something that definitely should be logged as a warning or error.

Usually a `StaleElementReferenceException` will more often than not result in retrying that piece of code. I can imagine that you want to see an error after all retries have been exhausted but still result in an `Exception`.
> I'm testing with the most basic pine script that just has a date picker: `date_picker = input.time(timestamp("1 Feb 2022 12:00"), title="Select start date")`

In general, trying to set and read pine script inputs is a pain. Users do all kind of things with it in creative and unexpected ways. Like using checkboxes as empty lines to separate different parts of the inputs like one would separate paragraphs.

**Comment by timelyart** [comment]
Fixed in [release v2.84](https://github.com/timelyart/Kairos/releases/tag/v2.84)

**Comment by mrcrdwd** [comment]
@timelyart really curious how you solved this one! But I think it's missing in the commit :) And thanks!

**Comment by timelyart** [comment]
The element's `clear()` method in combination with the date picker made it lose focus somehow. It is a miracle I figured it out this fast.

**Comment by mrcrdwd** [comment]
@timelyart can push the commit? :)

**Comment by timelyart** [comment]
Whoops! Done.
